# Generated by Django 3.1 on 2020-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='content',
            new_name='wiadomość',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='sex',
        ),
        migrations.AddField(
            model_name='contactform',
            name='płeć',
            field=models.CharField(choices=[('Od_Spottera', 'Od Spottera'), ('Od_Spotterki', 'Od Spotterki'), ('Od_Helikoptera_bojowego', 'Od Helikoptera Bojowego'), ('Od_Dymiana', 'Od Dymiana')], default='-------', max_length=500),
            preserve_default=False,
        ),
    ]
