# Generated by Django 3.1 on 2020-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200927_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='email',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='płeć',
            field=models.CharField(choices=[('Od_Spottera', 'Od Spottera'), ('Od_Spotterki', 'Od Spotterki')], max_length=500),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='wiadomość',
            field=models.TextField(max_length=500),
        ),
    ]
